NumPy is a linear algebra library in Python, the reaso nwhy it is important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of thier main building blocks

In [1]:
import numpy as np

# Numpy Arrays

In [2]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
randlist = np.arange(0,10,2) # first number, last number , step size
randlist # returns an array within the range of numbers

array([0, 2, 4, 6, 8])

In [13]:
# generate a numpy array of zeroes
zeroes_1d = np.zeros(4)
zeroes_1d

array([0., 0., 0., 0.])

In [17]:
zeroes_2d = np.zeros((4,4))
zeroes_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
ones_1d = np.ones(5)
ones_1d

array([1., 1., 1., 1., 1.])

In [19]:
ones_2d = np.ones((5,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

Linspace should not be compared with arange since linspace considers the number of points within the given range of numbers

In [21]:
lins = np.linspace(2,100,30)
lins # returns 1D array

array([  2.        ,   5.37931034,   8.75862069,  12.13793103,
        15.51724138,  18.89655172,  22.27586207,  25.65517241,
        29.03448276,  32.4137931 ,  35.79310345,  39.17241379,
        42.55172414,  45.93103448,  49.31034483,  52.68965517,
        56.06896552,  59.44827586,  62.82758621,  66.20689655,
        69.5862069 ,  72.96551724,  76.34482759,  79.72413793,
        83.10344828,  86.48275862,  89.86206897,  93.24137931,
        96.62068966, 100.        ])

# Identity Matrix

In [23]:
Identity = np.eye(3)
Identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random numbers array

In [26]:
random_numbers_1d= np.random.rand(5)
random_numbers # returns 1D array

array([0.18176455, 0.66043934, 0.64054253, 0.09305599, 0.03686761])

In [27]:
random_numbers_2d = np.random.rand(5,5)
random_numbers_2d

array([[0.57063235, 0.83990581, 0.47986016, 0.99836795, 0.04104002],
       [0.03183849, 0.30615143, 0.74025816, 0.61899664, 0.78297016],
       [0.95905158, 0.99760511, 0.71914944, 0.20962551, 0.88113639],
       [0.93270602, 0.42285515, 0.79366614, 0.01684069, 0.52064617],
       [0.30283186, 0.31660179, 0.53622229, 0.16778822, 0.91246443]])

In [ ]:
rand_int = np.random.randint(1,100,10) 
#the first two numbers denote the lower value to the highest value any random number selection,
#the next arguments denotes the number of elements or numbers to be selected from the range
rand_int # returns 1D array

# Reshape 

In [35]:
#lins
reshaped_array = lins.reshape(10,3)
reshaped_array

array([[  2.        ,   5.37931034,   8.75862069],
       [ 12.13793103,  15.51724138,  18.89655172],
       [ 22.27586207,  25.65517241,  29.03448276],
       [ 32.4137931 ,  35.79310345,  39.17241379],
       [ 42.55172414,  45.93103448,  49.31034483],
       [ 52.68965517,  56.06896552,  59.44827586],
       [ 62.82758621,  66.20689655,  69.5862069 ],
       [ 72.96551724,  76.34482759,  79.72413793],
       [ 83.10344828,  86.48275862,  89.86206897],
       [ 93.24137931,  96.62068966, 100.        ]])

# Max and Min Value and index location of array

In [37]:
print(random_numbers_2d.max())

0.998367948931742


In [38]:
print(random_numbers_2d.min())

0.016840690073504083


In [39]:
print(random_numbers_2d.argmin()) # returns index position of minimum value in that array
print(random_numbers_2d.argmax()) # returns index position of maximum value in that array

18
3


In [41]:
random_numbers_2d.shape

(5, 5)

In [42]:
# to check the data type of the array
random_numbers_2d.dtype

dtype('float64')