In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [5]:
# add two arrays
arr2 = arr.copy()

In [6]:
arr3 = arr2+arr2
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr4 = arr2-arr2
arr4


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr5 = arr2*arr2
arr5

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
# add scalar to an array
arr6 = arr5+100
arr6

array([100, 101, 104, 109, 116, 125, 136, 149, 164, 181, 200])

In [13]:
arr6/arr5 # gives a warning and returns infinity

C:\Users\user\AppData\Local\Temp/ipykernel_15092/3292504825.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr6/arr5


array([         inf, 101.        ,  26.        ,  12.11111111,
         7.25      ,   5.        ,   3.77777778,   3.04081633,
         2.5625    ,   2.2345679 ,   2.        ])

In [15]:
arr7 = arr2**arr2
arr7

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [16]:
# Square root of an array
arr8 = np.sqrt(arr7)
arr8

array([1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 5.19615242e+00,
       1.60000000e+01, 5.59016994e+01, 2.16000000e+02, 9.07492700e+02,
       4.09600000e+03, 1.96830000e+04, 3.75508376e+04])

In [19]:
# Exponential of an array
arr9 = np.exp(arr)
arr9

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [21]:
arr10 = np.log(arr) # throws an error since log of 0 is infinity
arr10

C:\Users\user\AppData\Local\Temp/ipykernel_15092/2358411363.py:1: RuntimeWarning: divide by zero encountered in log
  arr10 = np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [22]:
# Trignometric functions
arr10 = np.sin(arr)
arr10

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])