In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[2] # note indexing starts from zero

2

In [4]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr2 = np.arange(0,11)

In [11]:
slice_of_Arr= arr2[:6]

In [12]:
slice_of_Arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_Arr[:] = 80

In [14]:
slice_of_Arr


array([80, 80, 80, 80, 80, 80])

In [16]:
arr2 # command plays around and changes the items in the original array also, 
# this is to avoid memory issues when associated with large data

array([80, 80, 80, 80, 80, 80,  6,  7,  8,  9, 10])

In [18]:
arr_copy =arr.copy() # you create a copy of that array and therefore 
# will not harm the data in the original array

In [20]:
arr_copy[0:6] =10

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr_copy

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

# Indexing a Matrix


In [24]:
arr_2d = [[5,10,15],[30,45,44],[23,32,54]]

In [31]:
arr_2d_np = np.array(arr_2d)
arr_2d_np

array([[ 5, 10, 15],
       [30, 45, 44],
       [23, 32, 54]])

In [32]:
arr_2d[0][0]

5

In [33]:
arr_2d[0]

[5, 10, 15]

In [34]:
arr_2d[1][1] # double bracket notation

45

In [36]:
arr_2d_np[2,1] # single bracket notation

32

In [37]:
arr_2d_np[:2,1:]

array([[10, 15],
       [45, 44]])

In [40]:
arr_2d_np[1:,:] # assignment

array([[30, 45, 44],
       [23, 32, 54]])

# Conditional Selection

In [41]:
conditional_arr = np.arange(0,11)

In [45]:
bool_arr = conditional_arr <5 
# checks every number inside the array for the following condition
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [46]:
conditional_arr[bool_arr]

array([0, 1, 2, 3, 4])

In [48]:
conditional_arr[conditional_arr>5]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()